### PR TITLE
SKALE-3505 Fix case if share.a!=0 and share.b==0

### PR DESCRIPTION
**Pull request by yavrsky**
Fix case if share.a!=0 and share.b==0

### CODE REVIEW

**Review by DimaStebaev — CHANGES_REQUESTED** [review]
The same problem is in:
- `_checkPairing` function
- `verify` function in `SkaleVerifier`

**Review by DimaStebaev — CHANGES_REQUESTED** [review]
SafeMath is missing.

**Review by payvint — DISMISSED** [review]
Good!

**Review by DimaStebaev — DISMISSED** [review]

**Review by payvint — DISMISSED** [review]
Good!

**Review by payvint — DISMISSED** [review]

**Review by DimaStebaev — DISMISSED** [review]

**Review by payvint — DISMISSED** [review]

**Review by DimaStebaev — APPROVED** [review]

**Review by payvint — APPROVED** [review]

**Pull request merged**
